[package]
name = "crawler-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "^0.11.10", features = ["blocking"] }
url = "2.2.2"
bytes = "^1.1.0"
tokio = { version = "^1.18.2", features = ["full"] }
select = "^0.5.0"
